### ISSUE TITLE
ReferenceError: global is not defined

### ISSUE THREAD

**Issue by jdelStrother** [jhurliman/just-performance#1]
Hi there - I use `limiter`, which looks to have introduced a dependency on just-performance in limiter 2.0.
just-performance doesn't seem to be compatible with browsers unless global has been polyfilled or transpiled - I get:

```
Uncaught (in promise) ReferenceError: global is not defined
    at Module../node_modules/just-performance/dist/esm/browser.js
    at __webpack_require__ (preload.32fca3e04de966f0dd6d.js:1403)
    at Module../node_modules/limiter/dist/esm/clock.js
    at __webpack_require__ (preload.32fca3e04de966f0dd6d.js:1403)
    at Module../node_modules/limiter/dist/esm/TokenBucket.js
    at __webpack_require__ (preload.32fca3e04de966f0dd6d.js:1403)
    at Module../node_modules/limiter/dist/esm/RateLimiter.js
    at __webpack_require__ (preload.32fca3e04de966f0dd6d.js:1403)
    at Module../node_modules/limiter/dist/esm/index.js
    at __webpack_require__ (preload.32fca3e04de966f0dd6d.js:1403)
```

Is this a packaging accident, or is it expected behaviour?

**Comment by jhurliman** [comment]
Just confirming, you are attempting to use the ECMAScript Module version of this library directly in a browser without any packager such as webpack?

**Comment by jdelStrother** [comment]
No, I'm using webpack 5 to package it.
Hmm... it seems like webpack (or babel?) transpiles `global` to window in my own javascript, but not for stuff in node_modules. I can't see where that's configured though, would you like me to try a smaller reproduction?

**Comment by jhurliman** [comment]
https://github.com/jhurliman/just-performance/pull/2 should address this
